### PR TITLE
Add PulseAudio Plugin

### PR DESCRIPTION
**Pull request by andrewbest-tri**

### CODE REVIEW

**Comment by andrewbest-tri** [comment]
Note: It's commented out of defaults. Store true was getting overwritten. 

Had to install: libasound2-plugins inside the container
tested by installing alsa-utils and then running speaker-test utility

**Comment by andrewbest-tri** [comment]
Hmm looks like you might need a desktop user logged in for pulseaudio to start

**Comment by stonier** [comment]
Whoa, help on google is pretty messy. The original solution in `groot_rocker` doesn't work, but I do have it working in wierd and wonderful ways I do not yet completely understand (e.g. I can get it working without `~/.config/pulse`). This is going to take a bit more looking into.

And yes, unless you've got pulse running systemwide (not recommended), it's going to need a user configuration. Trying to run it headless?

**Comment by andrewbest-tri** [comment]
I was indeed running it on a machine through SSH. If my user isn't also logged in visually, pulse isn't running and I can't forward sound. 
So I have to remote into the machine, log it in at the desktop, then I can do rocker through SSH.

**Comment by stonier** [comment]
Pending on https://github.com/stonier/groot_rocker/pull/34/files (validate env and required extension checks). Some additional info for reference:

* Endeavoured to accommodate `root` as a user, but it needs the exact same user id's for permissions
* Uses the new `required_extensions` functionality, so it throws when `--user` is not also used
* Checks for the shared socket in `validate_environment`, throws if it can't find it
* Consolidated the socket path lookups to exclusively use freedesktop's `XDG_RUNTIME_DIR` variable

**Comment by stonier** [comment]
Implementing just the logged-in-user forwarding of PulseAudio here. Issue #31 covers the case for a headless system.

**Review by stonier — APPROVED** [review]

**Comment by stonier** [comment]
Released in `groot_rocker:0.4.0`, `groot_rocker_extensions:0.4.0`.

**Pull request merged**
